#!/usr/bin/env bash
# ==============================================================================
# trace32_auto launcher - the single entry point used by the VS Code tasks.
#
#   t32.sh flash     flash the ELF, load symbols, run, start the DAP adapter
#   t32.sh load      load symbols into the running target, start DAP adapter
#   t32.sh rtt       interactive SEGGER RTT terminal
#   t32.sh open      start PowerView only
#   t32.sh stop      stop the DAP adapter started by this script
#
# PowerView is started once and then reused: every later invocation drives the
# already running instance through the TRACE32 Remote API (RCL).
#
# Building is deliberately out of scope - cargo, make, cmake and friends are the
# project's business. Chain the project's own build task with "dependsOn" in
# .vscode/tasks.json; this script only ever consumes the finished ELF.
# ==============================================================================

set -euo pipefail

TOOLKIT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_FILE="$TOOLKIT_DIR/config.env"
RUN_DIR="$TOOLKIT_DIR/.run"

die() { printf 'trace32_auto: %s\n' "$*" >&2; exit 1; }
info() { printf '\033[1;36m[t32]\033[0m %s\n' "$*"; }

[[ -f $CONFIG_FILE ]] || die "config not found: $CONFIG_FILE"

# Defaults; config.env overrides whatever it sets.
PROJECT_ROOT=".."
PROGRAM_NAME=""
ELF=""
T32_CPU=""
T32_CORES="1."
T32_MEMACCESS="AXI"
T32_JTAG_CLOCK="25MHz"
T32_DUALPORT="ON"
T32_FLASH_SCRIPT=""
T32_FLASH_ARGS=""
T32_SYS=""
T32_HOST=""
T32_EXE="t32marm-qt"
T32_BIN=""
T32_CONFIG=""
T32_REM=""
T32_DEBUG_ADAPTER=""
T32_RCL_PORT="20000"
T32_DAP_PORT="58870"
T32_TIMEOUT="600"

# shellcheck source=/dev/null
source "$CONFIG_FILE"

abs_path() {
    case "$1" in
        /*) printf '%s\n' "$1" ;;
        *)  printf '%s\n' "$2/$1" ;;
    esac
}

PROJECT_DIR="$(cd "$(abs_path "$PROJECT_ROOT" "$TOOLKIT_DIR")" 2>/dev/null && pwd)" \
    || die "PROJECT_ROOT does not resolve to a directory: $PROJECT_ROOT"

[[ -n $ELF ]] || die "ELF is empty in config.env"
ELF_PATH="$(abs_path "$ELF" "$PROJECT_DIR")"

# "~~/..." is TRACE32's own installation-directory prefix. Leave it alone and
# let PRACTICE expand it; only plain relative paths are ours to resolve.
FLASH_PATH=""
if [[ -n $T32_FLASH_SCRIPT ]]; then
    case "$T32_FLASH_SCRIPT" in
        '~~'*) FLASH_PATH="$T32_FLASH_SCRIPT" ;;
        *)     FLASH_PATH="$(abs_path "$T32_FLASH_SCRIPT" "$TOOLKIT_DIR")" ;;
    esac
fi

# TRACE32 is installed outside the project, so its paths are the only absolute
# ones here. Derive them all from T32_SYS unless the key was set explicitly.
[[ -n $T32_SYS ]] || T32_SYS="$HOME/t32"

if [[ -z $T32_HOST ]]; then
    case "$(uname -s)" in
        Darwin) T32_HOST="macosx64" ;;
        Linux)  T32_HOST="linux64" ;;
        *) die "cannot auto-detect the TRACE32 host directory on $(uname -s); set T32_HOST in config.env" ;;
    esac
fi

[[ -n $T32_BIN ]]           || T32_BIN="$T32_SYS/bin/$T32_HOST/$T32_EXE"
[[ -n $T32_REM ]]           || T32_REM="$T32_SYS/bin/$T32_HOST/t32rem"
[[ -n $T32_CONFIG ]]        || T32_CONFIG="$T32_SYS/config.t32"
[[ -n $T32_DEBUG_ADAPTER ]] || T32_DEBUG_ADAPTER="$T32_SYS/demo/env/vscode/bin/$T32_HOST/t32debugadapter"

# TRACE32 splits CMM arguments on whitespace, so these paths cannot contain any.
for path in "$TOOLKIT_DIR" "$ELF_PATH" "$FLASH_PATH"; do
    if [[ $path == *[[:space:]]* ]]; then
        die "path must not contain spaces: $path"
    fi
done

# ------------------------------------------------------------------------------
# helpers
# ------------------------------------------------------------------------------

port_open() { (exec 3<>"/dev/tcp/127.0.0.1/$1") >/dev/null 2>&1; }

wait_port() {
    local port=$1 timeout=$2 waited=0
    while ! port_open "$port"; do
        sleep 0.2
        waited=$((waited + 1))
        (( waited > timeout * 5 )) && return 1
    done
    return 0
}

wait_file() {
    local file=$1 timeout=$2 waited=0
    while [[ ! -f $file ]]; do
        sleep 0.2
        waited=$((waited + 1))
        (( waited > timeout * 5 )) && return 1
    done
    return 0
}

# Translate config.env into PRACTICE globals. Doing it in bash keeps all
# quoting rules in one language and keeps the CMM scripts free of parsing.
write_cmm_config() {
    mkdir -p "$RUN_DIR"
    cat >"$RUN_DIR/config.cmm" <<EOF
; Generated by scripts/t32.sh from config.env. Do not edit.

GLOBAL &CFG_ROOT &CFG_RUNDIR &CFG_PROJECT_DIR &CFG_PROGRAM &CFG_ELF
GLOBAL &CFG_CPU &CFG_CORES &CFG_MEMACCESS &CFG_JTAG_CLOCK &CFG_DUALPORT
GLOBAL &CFG_FLASH_SCRIPT &CFG_FLASH_ARGS

&CFG_ROOT="$TOOLKIT_DIR"
&CFG_RUNDIR="$RUN_DIR"
&CFG_PROJECT_DIR="$PROJECT_DIR"
&CFG_PROGRAM="$PROGRAM_NAME"
&CFG_ELF="$ELF_PATH"
&CFG_CPU="$T32_CPU"
&CFG_CORES="$T32_CORES"
&CFG_MEMACCESS="$T32_MEMACCESS"
&CFG_JTAG_CLOCK="$T32_JTAG_CLOCK"
&CFG_DUALPORT="$T32_DUALPORT"
&CFG_FLASH_SCRIPT="$FLASH_PATH"
&CFG_FLASH_ARGS="$T32_FLASH_ARGS"

ENDDO
EOF
}

start_powerview() {
    if port_open "$T32_RCL_PORT"; then
        info "reusing PowerView on RCL port $T32_RCL_PORT"
        return
    fi
    [[ -x $T32_BIN ]] \
        || die "PowerView not executable: $T32_BIN (check T32_SYS / T32_HOST / T32_EXE in config.env)"
    [[ -f $T32_CONFIG ]] \
        || die "TRACE32 config not found: $T32_CONFIG (check T32_SYS or set T32_CONFIG in config.env)"

    rm -f "$RUN_DIR/ready"
    info "starting PowerView"
    (
        cd "$PROJECT_DIR"
        T32AUTO_DIR="$TOOLKIT_DIR" nohup "$T32_BIN" \
            -c "$T32_CONFIG" \
            -s "$TOOLKIT_DIR/scripts/startup.cmm" "$TOOLKIT_DIR" \
            >"$RUN_DIR/powerview.log" 2>&1 &
        disown
    )
    wait_port "$T32_RCL_PORT" 120 \
        || die "PowerView did not open RCL port $T32_RCL_PORT (check RCL=NETTCP in $T32_CONFIG)"
    wait_file "$RUN_DIR/ready" 60 \
        || die "PowerView started but startup.cmm never finished"
    info "PowerView ready"
}

# Run a CMM through RCL and block until it reports back. t32rem itself returns
# as soon as the command is queued, so the script writes .run/done when it ends.
t32_do() {
    local script=$1; shift
    local stamp="$RUN_DIR/done"
    [[ -x $T32_REM ]] \
        || die "t32rem not executable: $T32_REM (check T32_SYS / T32_HOST in config.env)"
    rm -f "$stamp"
    "$T32_REM" localhost protocol=NETTCP port="$T32_RCL_PORT" wait=10000 \
        DO "$script" "$@" >/dev/null
    wait_file "$stamp" "$T32_TIMEOUT" \
        || die "TRACE32 script did not finish within ${T32_TIMEOUT}s - check the PowerView AREA window"

    # The file appears before PowerView has flushed it; give the write a moment.
    local status=""
    local attempt
    for attempt in 1 2 3 4 5 6 7 8 9 10; do
        status="$(tr -d '\r\n' <"$stamp")"
        if [[ -n $status ]]; then
            break
        fi
        sleep 0.1
    done

    [[ $status == OK ]] || die "TRACE32 reported: ${status:-<empty status file>}"
}

start_adapter() {
    [[ -n $T32_DEBUG_ADAPTER ]] || return 0
    if port_open "$T32_DAP_PORT"; then
        info "debug adapter already listening on $T32_DAP_PORT"
        return
    fi
    [[ -x $T32_DEBUG_ADAPTER ]] \
        || die "debug adapter not executable: $T32_DEBUG_ADAPTER (check T32_SYS / T32_HOST in config.env)"
    info "starting t32debugadapter on port $T32_DAP_PORT"
    (
        nohup "$T32_DEBUG_ADAPTER" --port "$T32_DAP_PORT" \
            >"$RUN_DIR/adapter.log" 2>&1 &
        echo $! >"$RUN_DIR/adapter.pid"
        disown
    )
    wait_port "$T32_DAP_PORT" 30 || die "debug adapter did not open port $T32_DAP_PORT"
}

# ------------------------------------------------------------------------------
# commands
# ------------------------------------------------------------------------------

case "${1:-flash}" in
    flash)
        [[ -n $FLASH_PATH ]] || die "T32_FLASH_SCRIPT is empty; use 'load' for RAM images"
        [[ -f $ELF_PATH ]] \
            || die "ELF not found: $ELF_PATH (build the project first, or fix ELF in config.env)"
        write_cmm_config
        start_powerview
        info "flashing $ELF_PATH"
        t32_do "$TOOLKIT_DIR/scripts/target.cmm" ACTION=flash "ROOT=$TOOLKIT_DIR"
        start_adapter
        info "flashed, symbols loaded, target running"
        ;;

    load)
        [[ -f $ELF_PATH ]] \
            || die "ELF not found: $ELF_PATH (build the project first, or fix ELF in config.env)"
        write_cmm_config
        start_powerview
        info "loading symbols from $ELF_PATH"
        t32_do "$TOOLKIT_DIR/scripts/target.cmm" ACTION=load "ROOT=$TOOLKIT_DIR"
        start_adapter
        info "symbols loaded, target running"
        ;;

    rtt)
        port_open "$T32_RCL_PORT" \
            || die "no PowerView on RCL port $T32_RCL_PORT - run the flash or load task first"
        exec python3 "$TOOLKIT_DIR/scripts/rtt_viewer.py" "${@:2}"
        ;;

    open)
        write_cmm_config
        start_powerview
        ;;

    adapter)
        start_adapter
        ;;

    config)
        write_cmm_config
        info "resolved TRACE32 installation paths"
        for entry in "T32_BIN=$T32_BIN" "T32_REM=$T32_REM" \
                     "T32_CONFIG=$T32_CONFIG" "T32_DEBUG_ADAPTER=$T32_DEBUG_ADAPTER"; do
            path="${entry#*=}"
            if [[ -e $path ]]; then
                printf '  ok      %s\n' "$entry"
            else
                printf '  MISSING %s\n' "$entry"
            fi
        done
        info "resolved target configuration -> $RUN_DIR/config.cmm"
        cat "$RUN_DIR/config.cmm"
        ;;

    stop)
        if [[ -f $RUN_DIR/adapter.pid ]]; then
            kill "$(cat "$RUN_DIR/adapter.pid")" 2>/dev/null || true
            rm -f "$RUN_DIR/adapter.pid"
            info "debug adapter stopped"
        else
            info "no adapter pid recorded"
        fi
        ;;

    *)
        die "unknown command '$1' (flash|load|rtt|open|adapter|stop|config)"
        ;;
esac
